### ISSUE TITLE
Crash with Artificial Foliage 1.4

### ISSUE THREAD

**Issue by Mysticpasta1** [finallion/Artificial_Foliage-FABRIC-#1]
Artificial Foliage 1.4 for 1.16.4-1.16.5
Fabric API 0.34.1

[12:18:10] [main/FATAL]: Mixin apply failed arfo.mixins.json:MixinFeature -> net.minecraft.class_3031: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on isSoil could not find any targets matching 'isSoil' in net.minecraft.class_3031. Using refmap fabric-example-mod-refmap.json [PREINJECT Applicator Phase -> arfo.mixins.json:MixinFeature -> Prepare Injections ->  -> handler$hgg002$isSoil(Lnet/minecraft/class_2248;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on isSoil could not find any targets matching 'isSoil' in net.minecraft.class_3031. Using refmap fabric-example-mod-refmap.json [PREINJECT Applicator Phase -> arfo.mixins.json:MixinFeature -> Prepare Injections ->  -> handler$hgg002$isSoil(Lnet/minecraft/class_2248;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at user11681.limitless.asm.LimitlessFabricMixinTransformerProxy.transformClassBytes(LimitlessFabricMixinTransformerProxy.java:92) ~[limitless-1.2.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at net.minecraft.class_2378.<clinit>(class_2378.java:204) ~[intermediary-1.16.5.jar:?]
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:85) ~[4697a69d-1f6c-4bd8-9864-722447ebdf50.jar:?]
	at io.github.redstoneparadox.paradoxconfig.codec.JanksonConfigCodec.<init>(JanksonConfigCodec.java:18) ~[f93aa77f-e80b-4330-ac8b-1627c953f94a.jar:?]
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.onPreLaunch(ParadoxConfig.java:21) ~[f93aa77f-e80b-4330-ac8b-1627c953f94a.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]

**Comment by finallion** [comment]
when did this happen?

**Comment by Mysticpasta1** [comment]
this was in a modpack I have, I just tried to add your mod and that happened

**Comment by finallion** [comment]
ok, I figured the issue. I will upload a new version in a couple of minutes. Let me know if it works now!

**Comment by Mysticpasta1** [comment]
occurring with 1.5, check DM on discord

**Comment by finallion** [comment]
Closed due to another mod causing the crash.
