### ISSUE TITLE
Conflict with Sodium in 1.16.5

### ISSUE THREAD

**Issue by d4rkm0nkey** [finallion/Artificial_Foliage-FABRIC-#3]
```
Mixin apply failed betterfoliage.mixins.json:MixinClientWorld -> net.minecraft.class_638: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_638::onRandomDisplayTick with priority 1000 cannot inject into net/minecraft/class_638::method_2943(IIIILjava/util/Random;ZLnet/minecraft/class_2338$class_2339;)V merged by me.jellysquid.mods.sodium.mixin.features.world_ticking.MixinClientWorld with priority 1000 [PREINJECT Applicator Phase -> betterfoliage.mixins.json:MixinClientWorld -> Prepare Injections ->  -> handler$zjd000$onRandomDisplayTick(IIIILjava/util/Random;ZLnet/minecraft/class_2338$class_2339;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_638::onRandomDisplayTick with priority 1000 cannot inject into net/minecraft/class_638::method_2943(IIIILjava/util/Random;ZLnet/minecraft/class_2338$class_2339;)V merged by me.jellysquid.mods.sodium.mixin.features.world_ticking.MixinClientWorld with priority 1000 [PREINJECT Applicator Phase -> betterfoliage.mixins.json:MixinClientWorld -> Prepare Injections ->  -> handler$zjd000$onRandomDisplayTick(IIIILjava/util/Random;ZLnet/minecraft/class_2338$class_2339;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by d4rkm0nkey** [comment]
I am dumb. Confused Artificial Foliage with Better Foliage. Sorry for that!
